CREATE DATABASE mvctestdb;

GRANT ALL PRIVILEGES ON mvctestdb.* TO 'ohgiraffers'@'%';

USE mvctestdb;

DROP TABLE IF EXISTS tbl_report CASCADE;


CREATE TABLE IF NOT EXISTS tbl_report
(
    REP_NO INT AUTO_INCREMENT COMMENT '신고 번호',
    REP_TITLE VARCHAR(150) NOT NULL COMMENT '신고 제목',
    REP_DATE DATE NOT NULL COMMENT  '신고 날짜',
    REP_REASON VARCHAR(1500) NOT NULL COMMENT '신고 사유',
    REP_RESULT VARCHAR(10) NOT NULL COMMENT '신고 결과',
    REP_PERSON VARCHAR(50) NOT NULL COMMENT '신고 회원 id',
    REP_DEP VARCHAR(50) NOT NULL COMMENT '신고 종류',
    CONSTRAINT pk_REP_NO PRIMARY KEY (REP_NO)
    ) ENGINE=INNODB COMMENT '신고';

SELECT * FROM tbl_report;

COMMIT;